// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2017-11-26 17:44:22.714737766 +0000 UTC m=+0.062030636

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "ecs-deploy is the glue between your CI and ECS. It automates deploys based a simple JSON file Edit",
        "title": "ecs-deploy",
        "contact": {
            "name": "Edward Viaene"
        },
        "license": {},
        "version": "0.0.1"
    },
    "paths": {
        "/api/v1/deploy/{service}": {
            "post": {
                "description": "Deploy a service to ECS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Deploy service to ECS",
                "operationId": "ecs-deploy-service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "service",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/api/v1/ecr/create/{repository}": {
            "post": {
                "description": "Creates AWS ECR (Docker) repository using repository name as parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create ECR repository",
                "operationId": "ecr-create-repository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "repository",
                        "name": "repository",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/api/v1/export/terraform": {
            "get": {
                "description": "Export service data stored in dynamodb into terraform tf files",
                "produces": [
                    "application/json"
                ],
                "summary": "Export current services to terraform",
                "operationId": "export-terraform"
            }
        },
        "/api/v1/healthcheck": {
            "get": {
                "description": "Healthcheck for loadbalancer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Healthcheck",
                "operationId": "healthcheck"
            }
        },
        "/login": {
            "post": {
                "description": "login with user and password to receive jwt token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "login to receive jwt token",
                "operationId": "login"
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
